class ImageNetwork {
  final String url;
  ImageNetwork({this.url});
}

var listImage = [
  ImageNetwork(
      url:
          "https://i.pinimg.com/originals/ea/41/ac/ea41ac323555e5db35b160e6082c7e97.png"),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwkCS0fAAIykx6NpZvUjNJwk6lEOqHa7fCGOcSzsOd-AoFc6khC5Xfi-rlwlKZpn_MqE0&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDu3Hq1SoIMIqXy6E46rTc141oBAIDpWwxH4HSD4JsHd9HZ25WnCdAjdooMyXOg-cFzoY&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTn0GI92S7vB8xOQfB9wzh0FnuM3unx91jwoLM8hgfwO5l3MFl9x0S6ajyYr7ZMOSp9m40&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxNW4onK-nKGwg0hPpxJ7Up3FrrhsVE_PbmuFgYf1PZjQ7Xba_imdtoEqyRqFv4mfshTk&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7xNxC-_VjsajMAMN5MTzWYgToo0aoJumai5Bo1FT5BM2eASuQ_uGiyZYEjc7agkvXuHU&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2W6e1x5z1zEZiomLofcGpfcl9PECwWP0P-Tz3dQhYpgndeIUem4tW4cUMHDYj9nD3jJ0&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2Hj7lnjl-R1QlOF8bb82RNF84062XEYXsRg&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://1.bp.blogspot.com/-bhru_3eLk8M/Xuca3vxWUBI/AAAAAAAAo7I/8WabKpy_QPkHnP1Fn8MWATlo1lMzhmsxgCLcBGAsYHQ/s1600/Hinh-nen-phong-canh-thien-nhien%2B%25281%2529.jpg",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQww376WAnvMBi6p_V5nFmTXc8e816RWqxQLTNHXzIY1yr-QQtisVuXlQvC2uRa4QULEsA&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfwcD9t0o4ONhdJYhmlmxmHoYtzowNle2aRvXMgB8Gcg6N0Hp67bnZhXZh4g7UNA6awZA&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc64hHQGm666ZK4XMJZaJIGIUH0N0DCau7SA&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBObFItuNPS-zwmYC0aOHgRHN2M1azpaE2udmhFsVPGBh5PVXrJu0Ty0CbGyzRQYpeBw&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAu9tSdWnopO-1Y37XYJrXDf5lSQZY-4KmZVe0Q3K156iuBz9HNFSiOibidMRustvx9Fk&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfUJkJWk6imOaTT6UDagW9sNT204TSciEAOAH9nUq1w04HFnhaitH_i2a7Um-sjTNg5IA&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzdze4Idio7wwoio7uhWnwF486mOaOizzNYg&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1XBYMmRRgLKkxOmuw6xStIILrLJFEshmZzg&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcr55kcuZbGEQqbPZ9C_-tWrFCY-2briV3fw&usqp=CAU",
  ),
  ImageNetwork(
    url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkjtdjklxhr65Zsvi-LzIw44b09BVC_KKWXA&usqp=CAU",
  ),
  ImageNetwork(
      url:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIYFmgh74VewMsq2B5_Sekch_zEUiGJYw4CQ&usqp=CAU")
];
